### ISSUE TITLE
Error when starting new meeting 

### ISSUE THREAD

**Issue by mohammed2049** [mconf/mconf-web#155]
BigBlueButton::BigBlueButtonException at /bigbluebutton/rooms/admin/join
Impossible to convert XML to hash. Error: Missing end tag for 'HR' (got "body")

server log:
Completed 500 Internal Server Error in 46ms (ActiveRecord: 0.5ms)

BigBlueButton::BigBlueButtonException - Impossible to convert XML to hash. Error: Missing end tag for 'HR' (got "body")
Line: 1
Position: 1002
Last 80 unconsumed characters:
:
   () home/mohammed/.rvm/gems/ruby-2.2.2/bundler/gems/bigbluebutton-api-ruby-1de61968bb21/lib/bigbluebutton_hash_to_xml.rb:13:in `rescue in from_xml'
   () home/mohammed/.rvm/gems/ruby-2.2.2/bundler/gems/bigbluebutton-api-ruby-1de61968bb21/lib/bigbluebutton_hash_to_xml.rb:7:in `from_xml'
   () home/mohammed/.rvm/gems/ruby-2.2.2/bundler/gems/bigbluebutton-api-ruby-1de61968bb21/lib/bigbluebutton_api.rb:675:in `send_api_request'
   () home/mohammed/.rvm/gems/ruby-2.2.2/bundler/gems/bigbluebutton-api-ruby-1de61968bb21/lib/bigbluebutton_api.rb:212:in `is_meeting_running?'
   () home/mohammed/.rvm/gems/ruby-2.2.2/bundler/gems/bigbluebutton_rails-8a730f9b7d88/app/models/bigbluebutton_room.rb:136:in `fetch_is_running?'
  app/controllers/custom_bigbluebutton_rooms_controller.rb:133:in `load_and_fetch_room_info'
  activesupport (4.1.11) lib/active_support/callbacks.rb:429:in `block in make_lambda'
  activesupport (4.1.11) lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
  activesupport (4.1.11) lib/active_support/callbacks.rb:501:in `block in call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:501:in `call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.11) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.11) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.11) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.11) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.11) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.11) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.11) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.11) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.11) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.11) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.11) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:692:in `call'
  xray-rails (0.1.16) lib/xray/middleware.rb:37:in `call'
  exception_notification (4.0.1) lib/exception_notification/rack.rb:28:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.11) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.11) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.11) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  actionpack (4.1.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.11) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.11) lib/rails/engine.rb:514:in `call'
  railties (4.1.11) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.5) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.1.11) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.11) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.11) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.11) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.11) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:10:in `<top (required)>'
  spring (1.3.4) lib/spring/client/rails.rb:28:in `call'
  spring (1.3.4) lib/spring/client/command.rb:7:in `call'
  spring (1.3.4) lib/spring/client.rb:26:in `run'
  spring (1.3.4) bin/spring:48:in `<top (required)>'
  spring (1.3.4) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `<main>'

**Comment by daronco** [comment]
This is a generic error that happens when Mconf-Web receives an unexpected response from the web conference server. This is very likely a configuration issue or an issue in your BigBlueButton server instead of a bug in Mconf-Web.

Check the information of the BigBlueButton server you configured in Mconf-Web. Check if the URL and shared secret are correct. Use exactly the same URL and shared secret in the API Mate (http://mconf.github.io/api-mate/) to check if your server is responding properly to API calls.

If the problem persist you can look for help in our mailing list (mconf-dev@googlegroups.com).

**Comment by mohammed2049** [comment]
@daronco thank you very much, I'm really appreciate your help
