### ISSUE TITLE
Web application could not be started

### ISSUE THREAD

**Issue by dragonarmor** [mconf/mconf-web#178]
I've tried to install mconf-web per https://github.com/mconf/mconf-web/wiki/Deployment
I keep getting this error when I try to access the website. Can someone help with this error? Thanks

/var/www/mconf-web/current/config/configatron/defaults.rb:50: syntax error, unexpected ':', expecting tASSOC
  "es-419": "Español",
           ^
/var/www/mconf-web/current/config/configatron/defaults.rb:50: syntax error, unexpected ',', expecting $end (SyntaxError)
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/configatron-2.13.0/lib/configatron/rails.rb:47:in `block in init'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/configatron-2.13.0/lib/configatron/rails.rb:44:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/configatron-2.13.0/lib/configatron/rails.rb:44:in `init'
  /var/www/mconf-web/current/config/initializers/configatron.rb:8:in `<top (required)>'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/engine.rb:648:in `block in load_config_initializer'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/notifications.rb:161:in `instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/engine.rb:647:in `load_config_initializer'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/engine.rb:611:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:30:in `instance_exec'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:30:in `run'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
  /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:44:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
  /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/initializable.rb:54:in `run_initializers'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/application.rb:300:in `initialize!'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `method_missing'
  /var/www/mconf-web/current/config/environment.rb:11:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/mconf-web/current/vendor/bundle/ruby/1.9.1/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:112:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by daronco** [comment]
@dragonarmor are you using the latest tag "v2.0.1"? Or which one?
Please paste here the contents of your file: `/var/www/mconf-web/current/config/configatron/defaults.rb`

Did you change any code in your application? There might be something different in your code or on your environment, let's try to figure out what it is.

**Comment by lfzawacki** [comment]
You're using ruby 1.9.1 which is not supported by the latest version (which is the one your following the guide for).

Follow the instructions starting from [here](https://github.com/mconf/mconf-web/wiki/Deployment#ruby) carefully and make sure you're using  **ruby 2.2.0** and that `rbenv version` returns the right version in the application directory before `bundle install`.

**Comment by daronco** [comment]
Hi @dragonarmor, is this solved or do you still having issues?

**Comment by daronco** [comment]
Closing due to the lack of feedback and since this was probably an issue with the version of ruby being used.
