### ISSUE TITLE
Wiki issue FYI

### ISSUE THREAD

**Issue by patriclougheed** [mconf/mconf-web#184]
Installing on Ubuntu 14.04.4 there is a know issue with Ruby 2.2.0 

see https://github.com/rbenv/ruby-build/issues/834

Installing 2.2.4 works fine though and you might want to update your wiki.

**Comment by daronco** [comment]
Are you sure this happens on 2.2.0? In the report they say 2.2.3 and 2.2.2.
We've been installing 2.2.0 on Ubuntu 14.04.4 and it works fine. I've installed a new server last week and had no issues.

It would be good to update to the latest ruby, I'm just checking to decide if we really need to do it now.

**Comment by patriclougheed** [comment]
Yup... just went through the deploy instructions and got the error in my ruby log. Tried twice with same results.

**Comment by daronco** [comment]
We just updated ruby to 2.2.5, which might solve this issue (e30e882e4c02a58b137fbe2887d3c78d6b4ffbb4).
This is not in the wiki yet, it will be updated when a new version of Mconf-Web is out.

**Comment by daronco** [comment]
Mconf-Web 2.3.0 was released and it uses ruby 2.2.5. Wiki pages updated as well.
