### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by nhtdata** [mconf/mconf-web#195]
Dear Team, need support from your end.
after run command 
passenger-install-apache2-module

i got error as below. (14.04.1-Ubuntu)
==

Sanity checking Apache installation...
Your Apache installation might be broken

You are about to install Phusion Passenger against the following
Apache installation:

  apxs2: /usr/bin/apxs2

However, this Apache installation appears to be broken, so this installer
cannot continue. To find out why this installer thinks the above Apache
installation is broken, run:

  export ORIG_PATH="$PATH"
  sudo -s -E
  export PATH="$ORIG_PATH"
  /home/mconf/.rbenv/versions/2.2.0/bin/ruby /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/bin/passenger-config --detect-apache2

It is also possible that your system has multiple Apache installations,
and that you are simply compiling Phusion Passenger against the wrong
Apache install. If this is the case, then the above command will also
advise you about what to do.

**Comment by daronco** [comment]
The error indicates that there's something wrong with your apache installation. 
Have you tried to follow the instructions in the error output?
It tells you that you might have two instances of apache. It even gives you a command to detect it. So try it out, it will probably give you more information on what's happening.
