### ISSUE TITLE
RAILS_ENV - installation

### ISSUE THREAD

**Issue by nhtdata** [mconf/mconf-web#196]
Dear Team,
need support from your end.  (14.04.1-Ubuntu)

root@mconf:/var/www/mconf-web/current# RAILS_ENV=production bundle exec rake db:drop db:create db:reset
Could not find rake-10.5.0 in any of the sources
Run `bundle install` to install missing gems.

**Comment by daronco** [comment]
What version of Mconf-Web are you installing? Which guide are you using?
It can't find rake, so it's probably something wrong with how you installed the gems.
See https://github.com/mconf/mconf-web/wiki/Deployment#download-the-application
