### ISSUE TITLE
[Suggestion] Sidekiq instead of Delayed_jobs

### ISSUE THREAD

**Issue by kirantpatil** [mconf/mconf-web#2]
Hi,

Lots of Rails projects have moved to Sidekiq for processing background jobs for below reason,
What if 1 Sidekiq process could do the work of 20 Resque or DelayedJob processes? 

For more information please visit, http://sidekiq.org/

Thanks for the great project.

**Comment by daronco** [comment]
Set status to rejected because we ended up going with Resque to replace DelayedJob.
