### ISSUE TITLE
Make it easier to install mconf-web

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#294]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 298, http://dev.mconf.org/redmine/issues/298

---

@Google user: leonardo...@gmail.com@

Currently, Mconf-Web can be installed manually or using mconf-web-conf.
mconf-web-conf can help the installation, but it is not as easy as it should be.

Ideally:
1. sudo apt-get install mconf-web
2. edit some configuration files
3. a utility script "mconf-web" would help with maintenance tasks such as restarting the server 

Some things to consider:
- Capistrano increases the complexity and it is not really necessary in most cases.
- In production RVM is also not really necessary. Maybe use a system-wide installation of RVM or maybe install Ruby from packages.
- It can be useful to package all gems with the application: "http://gembundler.com/man/bundle-package.1.html" rel="nofollow":http://gembundler.com/man/bundle-package.1.html

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-10-20T02:00:00Z

---

@Google user: leonardo...@gmail.com@

There other alternatives to Ubuntu packages, such as Chef and Moonshine.

Moonshine uses Capistrano and Puppet and can setup almost the entire server environment. It's certainly an improvement over the Capistrano/manual current setup process.

There's a branch in Mconf-Web being used to test it:
  "https://github.com/mconf/mconf-web/tree/moonshine" rel="nofollow":https://github.com/mconf/mconf-web/tree/moonshine 

Chef was not tested yet.


Moonshine: "https://github.com/railsmachine/moonshine" rel="nofollow":https://github.com/railsmachine/moonshine 
Puppet: "http://puppetlabs.com/" rel="nofollow":http://puppetlabs.com/ 
Chef: "http://wiki.opscode.com/display/chef/Home" rel="nofollow":http://wiki.opscode.com/display/chef/Home

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-04-08T15:51:39Z

---

We currently have two methods to install Mconf-Web:

1. Manually by following the installation guide in the wiki: https://github.com/mconf/mconf-web/wiki/Deployment
1. Using Chef with the cookbook at: https://github.com/mconf-cookbooks/mconf-web

Both are valid options. The first one "teaches" the user more about the process, but requires more time to complete and to maintain.
The second is the one we use internally, but it's not very polished yet for everyone to use. It still needs to be improved with examples, a step-by-step guide and so on.
We could keep both options available. 

Making Mconf-Web easier to install goes together with our goal of making all versions available in Mconf.org, with links to download, to learn how to install, etc.

**Comment by daronco** [comment]
For now we're good with the wiki page (https://github.com/mconf/mconf-web/wiki/Deployment).

I'll close this and we can open new issues for specific installation methods we might want to implement in the future.
