### ISSUE TITLE
On the "invite people for a community", filter the users list to remove the users that are members already

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#309]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 313, http://dev.mconf.org/redmine/issues/313

---

@Google user: fceca...@gmail.com@

When I'm going to invite someone to join a community, it would be better if those people who are already in the community don't appear in the search and also in the "show all users" option - it should be filtered previosly.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-10-10T03:00:00Z

---

@Google user: leonardo...@gmail.com@

**Comment by daronco** [comment]
This is still not implemented, reopening.

**Comment by daronco** [comment]
Duplicates https://github.com/mconf/mconf-web/issues/731.
