### ISSUE TITLE
Add a captcha to the registration form

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#335]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 369, http://dev.mconf.org/redmine/issues/369
Original Date: 2012-08-27
Original Assignee: Leonardo Daronco

---

Add some kind of captcha in the user registration form.

One option is: https://github.com/phatworx/devise_security_extension

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Maurício Cruz** (Maurício Cruz)
Original Date: 2012-08-30T19:32:42Z

---

three step implementation:

 to create a reCAPTCHA key:
https://www.google.com/recaptcha/admin/create

 display on page:
https://developers.google.com/recaptcha/docs/display

 verify
https://developers.google.com/recaptcha/docs/verify




main reCaptcha site:
https://developers.google.com/recaptcha/

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2013-06-23T23:07:52Z

---

Implemented in the branch master with recaptcha, see issue #727.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2013-06-25T01:43:34Z

---

Commits made at master that should be migrated:

* https://github.com/mconf/mconf-web/commit/d591a1a9b146dcd719cde6b9ade7c7a72a689568
* https://github.com/mconf/mconf-web/commit/f317ebbb69ffb1d137e8aed9cc36315ef1fd0087
* https://github.com/mconf/mconf-web/commit/a890d345e3a4185be7bee94ce0aa589c47bee729

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-10-13T20:47:25Z

---

See https://github.com/mconf/mconf-web/pull/126

**Comment by daronco** [comment]
Implemented by PR #126.
