### ISSUE TITLE
Problems with .svg files

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#353]
---

Author Name: **Fernando Bottin** (Fernando Bottin)
Original Redmine Issue: 415, http://dev.mconf.org/redmine/issues/415
Original Date: 2012-09-13

---

Rmagick does not manipulate correctly the svg images, thus "default event logos"  or any other svg image can't be used inside the site. I think it's needed to review the gem or find other better to do it.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-08-04T01:04:19Z

---

This will be fixed together with #978.

**Comment by daronco** [comment]
Fixed by PR #193. SVG files are not accepted anymore.
