### ISSUE TITLE
Rails 4 translations for model attributes and error messages

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#369]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 460, http://dev.mconf.org/redmine/issues/460
Original Date: 2012-10-10

---

In rails 4 there is a standard way to define translations for model attributes and error messages, and we should use it. It's not being used anywhere in the app yet, so we should test it, define how we will use it, and review all models to start using it.

See: http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-08-04T01:18:34Z

---

This is being changed for a while already as other issues are developed.

I'm leaving the ticket open so we can review it again in the future when possible all strings are using this standard.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-04-08T15:58:42Z

---

Inherited resources (#768) has also standard places to put translations, so it's a big help on organizing strings in controllers.

This information should be put in our best practices guide at some point (https://github.com/mconf/mconf-web/wiki/Style-Conventions).

**Comment by daronco** [comment]
This already an ongoing work and part of the standard development in the application.
