### ISSUE TITLE
Use Inherited Resources in the controllers

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#418]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 768, http://dev.mconf.org/redmine/issues/768
Original Date: 2013-05-13
Original Assignee: Lucas Zawacki

---

Inherited Resources (https://github.com/josevalim/inherited_resources) is a gem that can help shrink the controllers a lot. We should consider using it.

**Comment by lfzawacki** [comment]
Almost all controllers (especially the big ones) now use InheritedResources after the PR #165. Notable controllers are:

* [ParticipantsController](https://github.com/mconf/mconf-web/pull/165/commits/9b2f74ea5f7312913d2663d403fb3669d7dd07b1)
* [EventsController](https://github.com/mconf/mconf-web/pull/165/commits/816ec21f567e6e5e20b43013c10f627c334d1959)
* [PostsController](https://github.com/mconf/mconf-web/pull/165/commits/d681fa1b1c91cdd8d630711052aec8b468aab4ea)
* [SpaceControllers](https://github.com/mconf/mconf-web/pull/165/commits/35f5c837661df946f75c92b85dcc9fbb272dab14)
* [UsersController](https://github.com/mconf/mconf-web/pull/165/commits/c928ba1b7b1c4e5ddac22cd8d36978b3db105175)

Closing.
