### ISSUE TITLE
Avatars from Gravatar

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#425]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 792, http://dev.mconf.org/redmine/issues/792
Original Date: 2013-05-28

---

Get the avatars from Gravatar by default if the user has not uploaded an image yet.
If the user uploaded his own avatar then it should be used instead of the one from Gravatar.
We should also tell the user somehow that his image was taken from Gravatar. Maybe a tooltip in the avatar or just a message in the page where the user goes to edit his picture.

**Comment by daronco** [comment]
Resolved by PR #160.

Using avatars from Gravatar is optional and only works for users (not for spaces, since they don't have an email). By default the integration is disabled.
If enabled, all user avatars will be fetched from Gravatar, unless the user uploaded an avatar to Mconf-Web.
