### ISSUE TITLE
Filter the types of images supported for logos

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#501]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 978, http://dev.mconf.org/redmine/issues/978

---

Filter the images that a user can upload to his avatar or a logo of a space. Some image formats will not be processed correctly, and file formats that are not images should not even be considered.

There's already some filtering being done at the model level, see: https://github.com/mconf/mconf-web/blob/532ba0fdf080b02c463b157384efc09b964aa86d/app/uploaders/logo_image_uploader.rb#L14

But there's more that should be done:

  * These formats should be tested and we should leave only the ones that are really supported (svg, for instance, doesn't work properly). 
  * The "open file dialog" should already filter only the files that are supported.
  * If the user manages to upload a file that is not supported, the modal that crops the images should show an error to make it clear to the user that the file is not supported. Currently it either shows an empty logo or shows the wrong view (not the crop view).

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2014-02-21T05:17:44Z

---

Now the upload tag uses accepts='image/*' and this makes most browsers by default show only image types on modals. Unfortunately we don't want every image type and accepts='.jpg,.jpeg,.png' works on Chrome, but Firefox still has some problems with this (it works, but the filetypes are not grouped and not show as default) here's a bug for it https://bugzilla.mozilla.org/show_bug.cgi?id=826185.

So as a compromise it's still showing some image types which we don't play well with, like gif and svg, but it's harder for users to screw up stuff.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-03-24T19:37:24Z

---

I've seen on https://bugzilla.mozilla.org/show_bug.cgi?id=826185 that the bug is fixed. Can you test it again?

Also, some things related to this issue were made on https://github.com/mconf/mconf-web/pull/84

**Comment by daronco** [comment]
Fixed by PR #193.
