### ISSUE TITLE
Investigate LimeSurvey to use as a feedback tool for web conferences

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#513]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1027, http://dev.mconf.org/redmine/issues/1027

---

Currently Mconf-Web allows an admin to set a URL to which a user is redirected when he leaves a web conference, asking for feedback about the session. Usually this link points to a form hosted on Google Docs, but LimeSurvey (http://www.limesurvey.org) is an open source option that could also be used.

Maybe nothing has to be changed in the code, maybe we should just test LimeSurvey and use it. But it is also possible that there is a better way to integrate Mconf-Web and LimeSurvey than just a link.

**Comment by daronco** [comment]
We'll keep using a single link to integrate with external services such as Google Docs or LimeSurvey. Admins can pick whatever they want to use.
