### ISSUE TITLE
Replace the list of recordings with a list of meetings plus recordings

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#535]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1064, http://dev.mconf.org/redmine/issues/1064

---

Instead of having a page with the recordings of a room, it should show a list of all the meetings held in that room, including when they happened and the links to the recordings, in case it was recorded.
Meetings should be listed even if they were not recorded.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-09-24T20:09:45Z

---

This was already done in the branch "bootstrap3":https://github.com/mconf/mconf-web/tree/bootstrap3

**Comment by daronco** [comment]
Done in the branch "v3".

Leaving it open for a final adjustment: change the URLs from `/recordings` to `/meetings`.

**Comment by daronco** [comment]
Finished in the branch `v3`.
