### ISSUE TITLE
Old logos are not removed from disk

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#537]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1068, http://dev.mconf.org/redmine/issues/1068

Original Assignee: Lucas Zawacki

---

When a user changes his avatar or the log of a space, usually the name of the image will change, and so new files will be created in the disk. The old logo images will not be used anymore, but they are not being removed from the disk as they should.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2015-01-29T17:35:29Z

---

Doesn't happen anymore. When a new logo is uploaded now the old one will be removed, maybe updates from older versions or errors could leave some files behind... we could make a script to delete them.

**Comment by lfzawacki** [comment]
Double checked and it's not happening in the latest version. Closing.
