### ISSUE TITLE
Highlight of results in the filter of users/spaces doesn't work with special characters

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#549]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1084, http://dev.mconf.org/redmine/issues/1084

Original Assignee: Roberta Robert

---

See an example in the image attached. It happens in the list of users and spaces in the management area.
When searching for words with special characters such as "é", the internal search works as it should, but the highlight will not highlight all the words found in the search. In short, the internal search in the controller is ignoring accents, while the highlight method in the view is not (but it should).

Other characters should also be tested to make sure the highlight is consistent with the internal search.

**Comment by mconf-daileon** [comment]
---

Original attachments:
* [mconf-web-filter-accents](https://cloud.githubusercontent.com/assets/1714273/15099213/01bd7594-1526-11e6-930d-7ea719299e9b.png)

---

**Comment by daronco** [comment]
Fixed by #188.
