### ISSUE TITLE
Update bootstrap to version 3

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#550]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1087, http://dev.mconf.org/redmine/issues/1087

---

Bootstrap version 3 is already out and the previous version, used currently by Mconf-Web, is not supported anymore. Mconf-Web should be updated to use the new version.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2013-12-17T18:28:48Z

---

Good migration guides:

* http://upgrade-bootstrap.bootply.com/
* http://bootply.com/bootstrap-3-migration-guide
* http://stackoverflow.com/questions/17974998/updating-bootstrap-to-version-3-what-do-i-have-to-do

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-10-14T19:32:08Z

---

This has been in progress in the branch bootstrap3 (https://github.com/mconf/mconf-web/tree/bootstrap3) for a while.

Several things other than the bootstrap library are being updated/improved:
* The overall design is being improved to be cleaner and simpler to use.
* Layouts are being reviewed to improve the use of divs and other tags in the site.
* Stylesheets are also being reviewed to be cleaner and use more components and variables.
* The design is now responsive, a first step towards making it better in mobile devices (#886)

**Comment by daronco** [comment]
Done in the branch "v3".
