### ISSUE TITLE
Notifications are sometimes shown more than once, "dragged" to a second page

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#559]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1143, http://dev.mconf.org/redmine/issues/1143

---

Sometimes error notifications are shown in the page where it happens but then are shown again in the next page the user goes to, where they shouldn't appear.
Doesn't always happen and I'm not sure how to reproduce it, but I've seen it and it has been reported by other users also.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-04-08T15:44:10Z

---

We need to find a way to reproduce it and confirm if it really happens in production.
This issue is usually seen in development only, but in these cases the environment and the application are unstable, so it's acceptable that it happens.

**Comment by daronco** [comment]
We haven't seen this happen anymore (specially in the branch "v3), considering as fixed.
