### ISSUE TITLE
Better search for events and spaces

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#592]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1218, http://dev.mconf.org/redmine/issues/1218

---

Instead of using select2 to search for events (in events/index) and spaces (in spaces/index), we could use a input that filters the results in the list of results, similarly to what is done in the list of users and spaces in the administration pages.
It seems a more complete solution than using select2 because it shows more information for the user and seems more "natural".

**Comment by daronco** [comment]
Already done for spaces in #911 and will be done for events in #917.
