### ISSUE TITLE
Can't edit user email in edit profile screen

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#600]
---

Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Redmine Issue: 1234, http://dev.mconf.org/redmine/issues/1234

---

How to reproduce:
1. Go to /users/:user_id/profile/edit
2. Fill in a new email
3. Send the form
4. Email has not changed

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-06-09T18:26:49Z

---

It happens because, by design, users can't change their emails in their account (see #336).

Maybe we should separate the email used in the account from the email used in the profile. The user might want to register with an email but have another email being public to other users. In this case the users should be able to change their profile email, even though they can't change their account email (see #1263).

Meanwhile, to fix this we should just make the input to change the email in @user/edit@ read-only, so the users will know it can't be edited.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Fernando Bottin** (Fernando Bottin)
Original Date: 2014-10-30T21:14:23Z

---

Modified the input email in profile/edit to read-only.

I will let this issue open to discuss a better approach.

**Comment by daronco** [comment]
Users should not be able to change their email, closing this.
