### ISSUE TITLE
Improve the options to playback/download recordings

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#709]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1482, http://dev.mconf.org/redmine/issues/1482

Original Assignee: Fernando Bottin

---

* On the link "Play", add the tooltip: "Plays the recording in an HTML5 page. The recording is not downloaded to your computer and will require Internet to be reproduced."
* On the link "Download", add the tooltip: "Downloads a vídeo file (uses the WebM format) with the recording. You can use this video file to watch the recording offline and to share this recording in other websites."
* On the link "Download HTML", add the tooltip: "Downloads an HTML page that you can use to reproduce the recording offline using your browser. Has all the features of the HTML player online plus the advantage of also working offline. Currently can only be reproduced using the Firefox browser."

Also, the link "Download" should force a download of the video file, preventing the browser from playing it.
HTML5 has an attribute "download" that could be used, but it has to be tested properly with different browsers and different download configurations. Should also be tested with real recordings, hosted in a recording server (since the server's configuration is important here).
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-03-28T18:59:03Z

---

See
* https://github.com/mconf/mconf-web/pull/98
* https://github.com/mconf/bigbluebutton_rails/pull/21

**Comment by zo0z** [comment]
Hello, 

Thank you for providing this great service and project. I was wondering if there is a way to convert the recorded html5 video to mp4 or other standard video format. My objective is to upload to Youtube eventually, so this is a needed feature on my side.

Thanks,
Azza

**Comment by daronco** [comment]
Hi @zo0z, please send your questions to our mailing list (mconf-dev@googlegroups.com) and someone will try to help you there.

**Comment by zo0z** [comment]
Thank you, appreciated.
Azza
