### ISSUE TITLE
Use a captcha when an anonymous user is registering in an event

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#729]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1553, http://dev.mconf.org/redmine/issues/1553

---

Currently users can simply enter an email and register. This generates internal objects and emails. Bots could easily abuse this form.

See #369

**Comment by daronco** [comment]
Implemented by PR #126 for issue #335.
