### ISSUE TITLE
Refactor join requests controller

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#750]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1682, http://dev.mconf.org/redmine/issues/1682

---

The controller for join requests has too much code in it and some of it is partially duplicated.
This leads to bugs as #1681 and possibly others that were not detected yet.

It needs some refactoring to move functionality to models/libs and make it cleaner and more efficient.

**Comment by daronco** [comment]
Since this issue was created a lot has changed in the controller. It looks better now and has more tests too. So I'm closing this. Further improvements in this controller should be done as they are done for any other part of the application.
