### ISSUE TITLE
Unify sites/edit and sites/show views

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#762]
---

Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Redmine Issue: 1731, http://dev.mconf.org/redmine/issues/1731
Original Date: 2015-08-10

---

They are kind of redundant and confusing, e.g, the user sees disabled fields in the show view and thinks something is wrong or the user does not find the edit button because the form is very long.

First step would be to skip the show view and just have '/site' be the edit form.

Additional cool stuff to have would be having the input with 'disabled=disabled' and when the user clicks to edit them enable with javascript. This would make things a little better because then the form wont post all the attributes to rails, just the ones that were edited.

**Comment by daronco** [comment]
Solved in the branch "v3". Now the action show redirects to edit and there's only the edit view available.
