### ISSUE TITLE
Review and normalize recent activities

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#800]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1810, http://dev.mconf.org/redmine/issues/1810

---

Recent activities have several attributes that make them very flexible, able to represent several types of activities.
However, this flexibility ended up making us use the attributes in different ways for different types of activities.

The activities we have should be reviewed and we should make sure their attributes are used in a consistent manner across different types of activities. If the attribute "recipient" is the user that performed the action in one activity, it should be the same for all other activities.
Moreover, the documentation for the recent activities (at the top of the @RecentActivity@ model) should be improved to have a real example of each type of activity we have available. This documentation can make it a lot easier to parse activities when needed.

**Comment by daronco** [comment]
The recent activities evolved since this issue was created and are more stable and with more documentation, so we can consider this issue closed.

There biggest thing still left for recent activities might just be #557.
