### ISSUE TITLE
Clearing room options that are set using checkboxes

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#802]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1812, http://dev.mconf.org/redmine/issues/1812

---

When setting the web conference room options, there are usually multiple values the user can choose from, and one of these values is the default value set on Mconf-Live/BigBlueButton. If a user doesn't explicitly set an option to a given value, this option should use the default value in the web conference server.
For options such as the default layout, this is solved by having a "<default>" option in the combo box, that sets this attribute to "NULL" in the database.

However, options that are set with checkboxes won't work this way. These options will always have a true or false value, regardless of whether the user changed it or not. 
So, whenever the options of a room are saved, all the options that use checkboxes will have their values saved in the database, so they won't be "NULL" anymore (i.e. they will not use the default of the web conference server). And there is no way to set them back to "NULL", even if the user wanted to do so.

Checkboxes could be changed to components other components that allow multiple values, such as combo boxes.
The "auto start audio" flag, for example, could become a combo box with the values:

```
<default>
Yes
No
```

Having options as "NULL" in the database is good because it gives more flexibility to the web conference server to set its default behavior. When the flag "auto start audio" became default in Mconf-Live/BigBlueButton, for example, some rooms had it set to false in Mconf-Web, even though it was just because the users saved the options, not necessarily choosing to have this specific flag as false.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-02-19T20:10:00Z

---

All boolean flags in a BigbluebuttonRoom should be considered.
But it should be done only for flags that become parameters in the API calls and have a default in the web conference server. Also, flags such as "record", for instance, don't need a third "null" value since they will always be informed in the API calls and we don't expect to ever use a default from the web conference server.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2016-03-03T19:27:38Z

---

What about having these fields as disabled until the user clicks to edit them? Since disabled fields are not sent to server with forms. Would require some simple javascript tricks on the client side, but would prevent normal users from messing with these advanced settings unintentionally.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-03-03T20:07:04Z

---

Seems like a good solution, but we also have to consider if we want to allow users to "clear" the field after setting them.
If we want to (and I believe we do), these fields should have a "clear" or "use default" option that disables the field and submits it as "nil" to the server.

**Comment by daronco** [comment]
These options are not available anymore for the users to edit.
Admins can still edit them, but it's not a checkbox anymore, it's a combo box and one of the options is to set the attribute to null.
