### ISSUE TITLE
Inputs to edit LDAP configurations should not be autocompleted

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#819]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1880, http://dev.mconf.org/redmine/issues/1880

Original Assignee: Roberta Robert

---

The inputs to edit the username and password for LDAP in sites/edit are being autocompleted with the username and password the user saves in the browser (seen on Firefox). These should not happen. None of the inputs in sites/edit should be autocompleted.

**Comment by daronco** [comment]
Fixed by PR #819.
