### ISSUE TITLE
Improve the selection of visible languages

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#825]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1891, http://dev.mconf.org/redmine/issues/1891

---

Now that we have a few languages available, the controls (checkboxes) used to select the visible languages in sites/edit/ are not very adequate anymore, and will tend to take even more space as the number of languages available grows.
These controls should be changed to something more dynamic, such as a select2 input or a select box a checkboxes for each item.

**Comment by daronco** [comment]
It is now a combo box, so it accommodates more languages.
