### ISSUE TITLE
Add options to enable/disable spaces and everything related to them

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#833]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1908, http://dev.mconf.org/redmine/issues/1908

---

In the same way events can be disabled, Mconf-Web should have an option to disable spaces and everything else that needs spaces to work (posts, attachments, etc).
This would allow Mconf-Web to be used as a very simple user portal with personal web conference rooms only.

**Comment by daronco** [comment]
Now there's an option `Site#spaces_enabled` to completely disable spaces and everything related to them.
