### ISSUE TITLE
Login page is displayed inside a modal window when it requires auth and the user is not logged in

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#848]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1955, http://dev.mconf.org/redmine/issues/1955

---

Some pages displayed in modal windows require authentication. If the user is not authenticated and tries to access one of them (usually happens if the user leaves the session open for a while and it signs out automatically), the modal window will display the login page inside it.
This login page looks bad in the modal and might not even work.

Instead of showing the login page in the modal window, the user should just be redirected to the sign in page.

**Comment by daronco** [comment]
It now shows an "unauthorized" error when an anonymous user tries to access a view that requires user authentication, even when it is rendered in a modal.

Also, the behavior of modal windows was changed by b20344d9ed35981221ce33a50476aa6da1fbe1fc. Now views that should be displayed in modals will only be displayed in modals, never in a standard page.
