### ISSUE TITLE
undefined method `current_user' for nil:NilClass

### ISSUE THREAD

**Issue by erik-de-neve** [mconf/mconf-web#861]
We receive many times an error with the following backtrace:

A NoMethodError occurred in background at 2016-06-01 15:41:46 +0200 :

  undefined method `current_user' for nil:NilClass
  /var/www/mconf-web/current/config/initializers/bigbluebutton_rails.rb:75:in `block (3 levels) in <top (required)>'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/current/config/initializers/bigbluebutton_rails.rb:75:in `block (3 levels) in <top (required)>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:14:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:14:in `resolve_value'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:308:in `block in prepare_parameters'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:308:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:308:in `prepare_parameters'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:283:in `prepare_settings'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/common.rb:250:in `create_activity'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/public_activity-1.4.1/lib/public_activity/actions/creation.rb:14:in `activity_on_create'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:224:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:503:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:503:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:503:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:503:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/callbacks.rb:306:in `_create_record'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/timestamp.rb:57:in `_create_record'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/persistence.rb:484:in `create_or_update'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/callbacks.rb:302:in `block in create_or_update'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:502:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:502:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/callbacks.rb:302:in `create_or_update'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/persistence.rb:103:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/validations.rb:51:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/attribute_methods/dirty.rb:21:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:208:in `transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:268:in `block in save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/transactions.rb:267:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/persistence.rb:34:in `create'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/bigbluebutton_rails-ca0406edb3f3/app/models/bigbluebutton_room.rb:327:in `update_current_meeting'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/bigbluebutton_rails-ca0406edb3f3/app/models/bigbluebutton_room.rb:126:in `fetch_meeting_info'
  /var/www/mconf-web/current/app/controllers/custom_bigbluebutton_rooms_controller.rb:113:in `load_and_fetch_room_info'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:143:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:501:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:501:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:501:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:501:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionview-4.1.14.2/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/routing/route_set.rb:80:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/routing/route_set.rb:48:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/journey/router.rb:73:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/routing/route_set.rb:690:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/cookies.rb:562:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.14.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:194:in `method_missing'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

**Comment by daronco** [comment]
This is definitely a bug, thanks for reporting.

From what I've seen it happens [here](https://github.com/mconf/mconf-web/blob/master/config/initializers/bigbluebutton_rails.rb#L75) because `ctrl` is not defined.
It makes sense since this code is not triggered from a controller, but from [a worker](https://github.com/mconf/bigbluebutton_rails/blob/master/app/workers/bigbluebutton_meeting_updater.rb#L16) that runs in background.

From my tests it seems that this has no big impact in the application, since the `BigbluebuttonMeeting` object and the recent activity are both being created, and apparently with all the correct attributes.

But it's a bug nevertheless, so it will be fixed.

**Comment by daronco** [comment]
Solved by #862.
