### ISSUE TITLE
Can not finished Passenger installing?????

### ISSUE THREAD

**Issue by thanhchinh** [mconf/mconf-web#867]
Which languages are you interested in?

Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Ruby
   ⬢  Python
   ⬡  Node.js
   ⬡  Meteor

--------------------------------------------

Checking for required software...

 * Checking for C compiler...
      Found: yes
      Location: /usr/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/bin/c++
 * Checking for Curl development headers with SSL support...
      Found: yes
      curl-config location: /usr/bin/curl-config
      Header location: /usr/include/curl/curl.h
      Version: libcurl 7.35.0
      Usable: yes
      Supports SSL: yes
 * Checking for OpenSSL development headers...
      Found: yes
      Location: /usr/include/openssl/ssl.h
 * Checking for Zlib development headers...
      Found: yes
      Location: /usr/include/zlib.h
 * Checking for Apache 2...
      Found: yes
      Location of httpd: /usr/sbin/apache2
      Apache version: 2.4.7
 * Checking for Apache 2 development headers...
      Found: yes
      Location of apxs2: /usr/bin/apxs2
 * Checking for Rake (associated with /usr/bin/ruby1.9.1)...
      Found: yes
      Location: /usr/bin/ruby1.9.1 /usr/local/bin/rake
 * Checking for OpenSSL support for Ruby...
      Found: yes
 * Checking for RubyGems...
      Found: yes
 * Checking for Ruby development headers...
      Found: yes
      Location: /usr/include/ruby-1.9.1/ruby.h
 * Checking for rack...
      Found: yes
 * Checking for Apache Portable Runtime (APR) development headers...
      Found: yes
      Location: /usr/bin/apr-1-config
      Version: 1.5.1
 * Checking for Apache Portable Runtime Utility (APU) development headers...
      Found: yes
      Location: /usr/bin/apu-1-config
      Version: 1.5.3

--------------------------------------------

Sanity checking Apache installation...
apache2: Syntax error on line 216 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/conf-enabled/mconf-passenger.conf: Cannot load /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so into server: /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so: cannot open shared object file: No such file or directory
apache2: Syntax error on line 216 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/conf-enabled/mconf-passenger.conf: Cannot load /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so into server: /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so: cannot open shared object file: No such file or directory
Your Apache installation might be broken

You are about to install Phusion Passenger against the following
Apache installation:

  apxs2: /usr/bin/apxs2

However, this Apache installation appears to be broken, so this installer
cannot continue. To find out why this installer thinks the above Apache
installation is broken, run:

  export ORIG_PATH="$PATH"
  sudo -s -E
  export PATH="$ORIG_PATH"
  /usr/bin/ruby1.9.1 /var/lib/gems/1.9.1/gems/passenger-4.0.59/bin/passenger-config --detect-apache2

It is also possible that your system has multiple Apache installations,
and that you are simply compiling Phusion Passenger against the wrong
Apache install. If this is the case, then the above command will also
advise you about what to do.

**Comment by thanhchinh** [comment]
sudo logrotate -s /var/lib/logrotate/status /etc/logrotate.d/mconf-web
error: skipping "/var/www/mconf-web/current/log/lograge_production.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/www/mconf-web/current/log/production.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/www/mconf-web/current/log/resque_scheduler.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/www/mconf-web/current/log/resque_workers_all.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

**Comment by daronco** [comment]
Try to install `apache2` first:

```
sudo apt-get install apache2
```

Then install passenger again.
We already updated the installation instructions to include this step. Let us know if it works for you.

**Comment by thanhchinh** [comment]
Dear daronco,
Thanks your help...
