### ISSUE TITLE
mconf + bbb 1.0

### ISSUE THREAD

**Issue by miquelangeld** [mconf/mconf-web#872]
Hi, I've installed mconf but I can't to stablish any videoconference. I get the generic error screen, the mconf current version it's fully compatible with bbb1.0?

I created a new one bbb server in the mconf management and once I get an error about the bbb version.

When I install if I configure 1.0 as a BBB version i get this error in rake process

    {:name=>"Default Server", :url=>"http://10.10.10.16/bigbluebutton/api", :salt=>"0a68f285a8c61f003e85582700f10164", :version=>"1.0"}
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Version is not included in the list

But in the doc in github says that the 1.0(beta) is supported

**Comment by miquelangeld** [comment]
I answer my self
Finally using the master checkout seems to accept the version.

**Comment by daronco** [comment]
Yes, the latest version (2.1.0) still had code requiring BigBlueButton <0.9, even though it would work with 1.0.
It's fixed on master and will be available in the next version.

**Comment by miquelangeld** [comment]
Still with problems, I opened a thread in the google group. Seems like mconf can't create rooms, I only see in the apache log calls to check if a room it's running but none when I try to create a room.

Thanks.
