### ISSUE TITLE
Prioritize amount of matches on searches when using multiple words

### ISSUE THREAD

**Issue by daronco** [mconf/mconf-web#890]
Currently, when searching for users to invite to a conference, for example, typing the user's first and last name is sometimes worse than just typing a single name.

Multiple words are split and searched with "or", so that all results that match one word _or_ the other are shown. This is good, but the results that match _both_ words should receive priority and be displayed at the top.

This happens for all searches in Mconf-Web and could be solved in all of them together.

**Comment by RafaFP** [comment]
When #900  and #898 get merged, we must add this implementation to their specific "search_by_terms" contexts.

**Comment by daronco** [comment]
I'm reopening this because the prioritization still needs to be implemented for other resources that have the method `search_by_terms`: Event, Space, BigbluebuttonRecording

**Comment by daronco** [comment]
Closed by #916.
What's left to be done is related to events and will be done at #917.
