### ISSUE TITLE
Feature query: WebRTC for video and data

### ISSUE THREAD

**Issue by shams-fls** [mconf/mconf-web#907]
Do you have plans to support WebRTC for video and data streaming? If yes, by when is the feature expected.
Thanks.

**Comment by raphaelnardoto** [comment]
Também aguardamos essa funcionalidade.

**Comment by daronco** [comment]
For Mconf-Web, no, we don't plan on having any type of real time content sharing implemented in the application.

For Mconf in general, yes. Mconf-Live is the web conference component of Mconf and it already uses WebRTC for audio. In the future it should also include WebRTC for video, but there are no release dates set for it.

Please post future questions to our mailing list at mconf-dev@googlegroups.com so we can concentrate the issues here to actual bugs and tasks.
