### ISSUE TITLE
Issue while migrating db

### ISSUE THREAD

**Issue by erik-de-neve** [mconf/mconf-web#912]
I've a issue while running: "RAILS_ENV=production bundle exec rake db:migrate" with the latest version (master):

mconf@mconf-web:/var/www/mconf-web/current$ RAILS_ENV=production bundle exec rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rake aborted!
NameError: uninitialized constant AddInvitationGroupToInvitations
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:238:in `const_get'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:238:in `block in constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `inject'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:769:in `load_migration'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:764:in `migration'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:759:in `disable_ddl_transaction'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:958:in `block in migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:955:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:955:in `migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:814:in `up'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:792:in `migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<top (required)>'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
/home/mconf/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/mconf/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
NameError: uninitialized constant AddInvitationGroupToInvitations
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:238:in `const_get'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:238:in `block in constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `inject'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/inflector/methods.rb:236:in `constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:769:in `load_migration'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:764:in `migration'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:759:in `disable_ddl_transaction'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:1043:in `ddl_transaction'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:959:in `block in migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:955:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:955:in `migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:814:in `up'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/migration.rb:792:in `migrate'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.14.2/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<top (required)>'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/mconf/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
/home/mconf/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/mconf/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate

**Comment by daronco** [comment]
It was an issue in the merge of a pull request (#906) that had just been merged.
