### ISSUE TITLE
[Bug] User isn't redirected to space's main tab after removes his admin role

### ISSUE THREAD

**Issue by hipoloco** [mconf/mconf-web#932]
When a user removes his admin role on a space, he isn't redirected to space's main tab:

![2017-02-03-110103_1280x1024_scrot](https://cloud.githubusercontent.com/assets/8184347/22594246/07c905ba-ea01-11e6-8ed5-d9073ec5b577.png)

**Comment by daronco** [comment]
What are the steps to reproduce this bug?
What do you mean by "removes his admin role"?

**Comment by hipoloco** [comment]
Steps:
- add two users on any space
- change their roles on the space from "User" to "Administrator"
- sign in with one of the space's admin
- go to "Admin" tab on the space
- change your own role from "Administrator" to "User"

**Comment by daronco** [comment]
Fixed by 624ac174b1d2e1c40099ed001d6666d5e72f5cdb.
