### ISSUE TITLE
Russian translation: invite not working (date format)

### ISSUE THREAD

**Issue by Melkin1968** [mconf/mconf-web#940]
When user interface is turned to RU and the user wants to invite people to his/her meeting, it throws custom_bigbluebutton_rooms.send_invitation.error_date_format error.
also, calendar appears in portuguese (?)

The same bug as #834, but in another language. Could you please correct it.

**Comment by daronco** [comment]
Fixed on master. If you don't want or can't upgrade your Mconf-Web, just apply [this commit](https://github.com/mconf/mconf-web/commit/0b666bc9de6c452b11ecc6117abaf303d71e4842) to whatever version you're using.

**Comment by Melkin1968** [comment]
I have upgraded my Mconf-Web and invites are working nice now. Thank you a lot.
