### ISSUE TITLE
Eorror: Web application could not  be started

### ISSUE THREAD

**Issue by angelfreedomv** [mconf/mconf-web#941]
Excuse me，please you help me how to solve this problem. thank you! 
The report is as follows:

Permission denied @ rb_sysopen - /var/www/mconf-web/current/log/lograge_production.log (Errno::EACCES)
  /usr/local/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
  /usr/local/lib/ruby/2.2.0/open-uri.rb:36:in `open'
  /usr/local/lib/ruby/2.2.0/open-uri.rb:36:in `open'
  /usr/local/lib/ruby/2.2.0/logger.rb:628:in `open_logfile'
  /usr/local/lib/ruby/2.2.0/logger.rb:584:in `initialize'
  /usr/local/lib/ruby/2.2.0/logger.rb:318:in `new'
  /usr/local/lib/ruby/2.2.0/logger.rb:318:in `initialize'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/logger.rb:45:in `initialize'
  /var/www/mconf-web/current/config/environments/production.rb:107:in `new'
  /var/www/mconf-web/current/config/environments/production.rb:107:in `block in <top (required)>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:210:in `instance_eval'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:210:in `configure'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:182:in `configure'
  /var/www/mconf-web/current/config/environments/production.rb:7:in `<top (required)>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/dependencies.rb:247:in `require'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/dependencies.rb:247:in `block in require'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/dependencies.rb:232:in `load_dependency'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.14.2/lib/active_support/dependencies.rb:247:in `require'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/engine.rb:593:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/engine.rb:593:in `block in <class:Engine>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:30:in `instance_exec'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:30:in `run'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:55:in `block in run_initializers'https://github.com/mconf/mconf-web/issues/941
  /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:44:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/lib/ruby/2.2.0/tsort.rb:413:in `call'
  /usr/local/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/initializable.rb:54:in `run_initializers'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/application.rb:300:in `initialize!'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.14.2/lib/rails/railtie.rb:194:in `method_missing'
  /var/www/mconf-web/current/config/environment.rb:11:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/local/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/local/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/local/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by angelfreedomv** [comment]
Ubuntu version: 14.04.5 lts
Ruby version:ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
Apache version: Server version: Apache/2.4.7 (Ubuntu) Server built:   Jul 15 2016 15:34:04
Mysql Server version: 5.5.54-0ubuntu0.14.04.1 (Ubuntu)

DigitalOcean VPS (2CPU 2GBRAM 40GBSSD )
System metrics

    ------------- General -------------
    Kernel version    : 4.4.0-66-generic
    Uptime            : 2h 7m 20s
    Load averages     : 0.12%, 0.03%, 0.07%
    Fork rate         : unknown

    ------------- CPU -------------
    Number of CPUs    :    2
    Average CPU usage :   0%  --   0% user,   0% nice,   0% system, 100% idle
      CPU 1           :   0%  --   0% user,   0% nice,   0% system, 100% idle
      CPU 2           :   0%  --   0% user,   0% nice,   0% system, 100% idle
    I/O pressure      :   0%
      CPU 1           :   0%
      CPU 2           :   0%
    Interference from other VMs:   0%
      CPU 1                    :   0%
      CPU 2                    :   0%

    ------------- Memory -------------
    RAM total         :   2000 MB
    RAM used          :    354 MB (18%)
    RAM free          :   1646 MB
    Swap total        :      0 MB
    Swap used         :      0 MB (-nan%)
    Swap free         :      0 MB
    Swap in           : unknown
    Swap out          : unknown

General Ruby interpreter information

    RUBY_VERSION = 2.2.5
    RUBY_PLATFORM = x86_64-linux
    RUBY_ENGINE = ruby
    RubyGems version = 2.4.5.1
    RubyGems paths = ["/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0"]

**Comment by daronco** [comment]
Hi @angelfreedomv, did you find a solution for this error?

The application doesn't have permission to write to `/var/www/mconf-web/current/log/lograge_production.log`. Check the permissions in `/var/www/mconf-web/current/log/`, make sure it's writable by `mconf`. If the file `lograge_production.log` doesn't exist, you can also try to create it, giving write permission for `mconf`.

For further questions please use our mailing list at mconf-dev@googlegroups.com.
