### ISSUE TITLE
Invite external people to spaces

### ISSUE THREAD

**Issue by erik-de-neve** [mconf/mconf-web#952]
Since last version (2.5.0 effd3f) it's not possible anymore to invite external people to a space?

if you go a space and then Admin => Admissions => Invite Users, you are not allowed to choose external users/e-mail addresses anymore, only known users are selectable.

Is this normal behavior?

Thanks,
Erik

**Comment by daronco** [comment]
You were never able to invite people that don't have an account to join a space. Only users with an account will be able to join and be part of a space.
Are you sure you used this feature before? Maybe you're confused because you can invite external people to join a **conference**?

**Comment by erik-de-neve** [comment]
you where right.
Sorry it was my mistake, you can close this (non) issue!

Sorry!
Erik
